Day-02/GreetingApp/GreetingApp/Controllers/GreeterController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using GreetingApp.Services;

namespace GreetingApp.Controllers
{
    public class GreeterController : Controller
    {
        private IGreeterService _greeterService;
        private readonly IDateTimeService _dateTimeService;

        public GreeterController(IGreeterService greeterService, IDateTimeService dateTimeService)
        {
            _greeterService = greeterService;
            _dateTimeService = dateTimeService;
        }

        public GreeterController()
        {
            _dateTimeService = new DateTimeService();
            _greeterService = new GreeterService(_dateTimeService);
        }

        public ViewResult Index()
        {
            return View(new GreetInput());
        }

        public ViewResult Greet(GreetInput greetInput)
        {
            //var greetInput = new GreetInput() {FirstName = firstName, LastName = lastName};
            //var fullName = string.Format("{0} {1}", firstName, lastName);
            //greetInput.Validate();
            if (!this.ModelState.IsValid)
                return View("Index", greetInput);
            var message =  _greeterService.Greet(greetInput.FullName);
            this.ViewBag.Message = message;

            if (_dateTimeService.GetCurrent().Hour < 12)
                return View("MorningView");
            return View("AfternoonView");
        }
    }

    /*public class GreetInput
    {
        
        public string FirstName { get; set; }
        public string LastName { get; set; }

        public string FullName
        {
            get { return string.Format("{0} {1}", FirstName, LastName); }
           
        }

        public IDictionary<string, string> ErrorMessages { get; set; }

        public GreetInput()
        {
            ErrorMessages = new Dictionary<string, string>();
        }

        public bool IsValid
        {
            get { return ErrorMessages.Count <= 0; }
        }

        public void Validate()
        {
            if (string.IsNullOrEmpty(FirstName))
                ErrorMessages.Add("FirstName", "First name cannot be empty!");
            if (string.IsNullOrEmpty(LastName))
                ErrorMessages.Add("LastName", "Last name cannot be empty!");

        }
    }*/

    public class GreetInput
    {
        [Required]
        public string FirstName { get; set; }

        [Required]
        public string LastName { get; set; }

        
        public string FullName
        {
            get { return string.Format("{0} {1}", FirstName, LastName); }
        }
    }
}

Day-02/GreetingApp/GreetingApp/Views/Greeter/AfternoonView.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>AfternoonView</title>
</head>
<body style="background-color: lightpink">
    <div>
        <h3>@ViewBag.Message</h3>
    </div>
</body>
</html>

Day-02/GreetingApp/GreetingApp/Views/Greeter/Index.cshtml
@using GreetingApp.Controllers
@model GreetingApp.Controllers.GreetInput
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>Index</title>
    <link href="/Content/Site.css" rel="stylesheet" />
</head>
    <body>
        <h1>Greeter</h1>
        @*  <form action="/Greeter/Greet" method="post">
            <label>Name :</label>
            <input type="text" name="FirstName" value="@Model.FirstName" />
            <input type="text" name="LastName" value="@Model.LastName" />
            <input type="submit" value="Greet" />
            <ul>
                @foreach (var item in Model.ErrorMessages)
                {
                    <li>@item.Value</li>    
                }
                
            </ul>
        </form>*@
        @*
        @using (Html.BeginForm("Greet", "Greeter"))
        {

            <label>Name :</label>
            <div>
                $1$ @Html.TextBoxFor(m => m.FirstName)    
                @Html.ValidationMessageFor(m => m.FirstName)#1#
                @Html.EditorFor(m => m.FirstName)
            </div>

            <div>
                @Html.TextBoxFor(m => m.LastName)    
                @Html.ValidationMessageFor(m => m.LastName)
            </div>
            <input type="submit" value="Greet" />
        
        }*@
        
        @using (Html.BeginForm("Greet", "Greeter"))
        {
            @Html.EditorForModel();
            <input type="submit" value="Greet"/>
        }
    </body>
</html>

Day-02/GreetingApp/GreetingApp/Views/Greeter/MorningView.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>MorningView</title>
</head>
<body style="background-color: lightblue">
    <div>
        <h3>@ViewBag.Message</h3>
    </div>
</body>
</html>

Day-02/GreetingApp/GreetingApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")" type="text/javascript"></script>
</head>

<body>
    @RenderBody()
</body>
</html>