Day-02/BugTrackerApp/BugTrackerApp/Models/Bug.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BugTrackerApp.Models
{
    public class Bug
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int Severity { get; set; }
    }
}

Day-02/BugTrackerApp/BugTrackerApp/Controllers/BugsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BugTrackerApp.Models;

namespace BugTrackerApp.Controllers
{
    [Authorize]
    public class BugsController : Controller
    {
        private BugTrackerAppContext db = new BugTrackerAppContext();

        //
        // GET: /Bugs/

        public ActionResult Index()
        {
            return View(db.Bugs.ToList());
        }

        //
        // GET: /Bugs/Details/5

        public ActionResult Details(int id = 0)
        {
            Bug bug = db.Bugs.Find(id);
            if (bug == null)
            {
                return HttpNotFound();
            }
            return View(bug);
        }

        //
        // GET: /Bugs/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Bugs/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Bug bug)
        {
                db.Bugs.Add(bug);
                db.SaveChanges();
                var isAjax = Request.IsAjaxRequest();
            return PartialView("BugRow", bug);
        }

        //
        // GET: /Bugs/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Bug bug = db.Bugs.Find(id);
            if (bug == null)
            {
                return HttpNotFound();
            }
            return View(bug);
        }

        //
        // POST: /Bugs/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Bug bug)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bug).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(bug);
        }

        //
        // GET: /Bugs/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Bug bug = db.Bugs.Find(id);
            if (bug == null)
            {
                return HttpNotFound();
            }
            return View(bug);
        }

        //
        // POST: /Bugs/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Bug bug = db.Bugs.Find(id);
            db.Bugs.Remove(bug);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        public ActionResult List()
        {
            return View(db.Bugs.ToList());
        }
    }
}

Day-02/BugTrackerApp/BugTrackerApp/Views/Bugs/BugRow.cshtml
@model BugTrackerApp.Models.Bug

 <tr>
        <td>
            @Html.DisplayFor(modelItem => modelItem.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => modelItem.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => modelItem.Severity)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
            @Html.ActionLink("Details", "Details", new { id=Model.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=Model.Id })
        </td>
    </tr>

Day-02/BugTrackerApp/BugTrackerApp/Views/Bugs/Create.cshtml
@model BugTrackerApp.Models.Bug

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@*//@using (Html.BeginForm("Create", "Bugs")) {*@
@using(Ajax.BeginForm("Create", new AjaxOptions(){HttpMethod = "Post", InsertionMode = InsertionMode.InsertAfter, UpdateTargetId = "bugsList"})){
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Bug</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Severity)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Severity)
            @Html.ValidationMessageFor(model => model.Severity)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Day-02/BugTrackerApp/BugTrackerApp/Views/Bugs/Delete.cshtml
@model BugTrackerApp.Models.Bug

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Bug</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Severity)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Severity)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Day-02/BugTrackerApp/BugTrackerApp/Views/Bugs/Details.cshtml
@model BugTrackerApp.Models.Bug

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Bug</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Severity)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Severity)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Day-02/BugTrackerApp/BugTrackerApp/Views/Bugs/Edit.cshtml
@model BugTrackerApp.Models.Bug

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Bug</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Severity)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Severity)
            @Html.ValidationMessageFor(model => model.Severity)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Day-02/BugTrackerApp/BugTrackerApp/Views/Bugs/Index.cshtml
@using BugTrackerApp.Models
@model IEnumerable<BugTrackerApp.Models.Bug>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @{
        Html.RenderPartial("Create", new Bug());
    }
</p>
<div id="bugsList">
    @{
    Html.RenderPartial("List",Model);
}    
</div>

Day-02/BugTrackerApp/BugTrackerApp/Views/Bugs/List.cshtml
@model IEnumerable<BugTrackerApp.Models.Bug>


<table id="bugsList">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Severity)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    Html.RenderPartial("BugRow", item);
}

</table>